/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tebk;

/**
 *
 * @author persada
 */
public class info extends javax.swing.JFrame {

    public info() {
        String bunga = "/tebk/2.2.png";
        String harimau = "/tebk/harimau.png";
        String kihajar = "/tebk/4.4.png";
        String sila = "/tebk/6.6.png";
        String dokter = "/tebk/5.5.png";
        String jokowi = "/tebk/3.3.png";
        String pulau = "/tebk/10.10.png";
        String rumah = "/tebk/8.8.png";
        String tari = "/tebk/9.9.png";
        String masjid = "/tebk/7.7.png";
        
        
        
        
        
        initComponents();
        String info = Home.segmen;
        if (info.equalsIgnoreCase("harimau")) {
            infogame.setIcon(new javax.swing.ImageIcon(getClass().getResource(harimau)));
        } else if (info.equalsIgnoreCase("bunga")) {
            infogame.setIcon(new javax.swing.ImageIcon(getClass().getResource(bunga)));
        } else if (info.equalsIgnoreCase("kihajar")) {
            infogame.setIcon(new javax.swing.ImageIcon(getClass().getResource(kihajar)));
        }else if (info.equalsIgnoreCase("sila")) {
            infogame.setIcon(new javax.swing.ImageIcon(getClass().getResource(sila)));
        }else if (info.equalsIgnoreCase("dokter")) {
             infogame.setIcon(new javax.swing.ImageIcon(getClass().getResource(dokter)));
        }else if (info.equalsIgnoreCase("jokowi")) {
            infogame.setIcon(new javax.swing.ImageIcon(getClass().getResource(jokowi)));
        }else if (info.equalsIgnoreCase("pulau")) {
            infogame.setIcon(new javax.swing.ImageIcon(getClass().getResource(pulau)));
        }else if (info.equalsIgnoreCase("rumah")) {
            infogame.setIcon(new javax.swing.ImageIcon(getClass().getResource(rumah)));
        }else if (info.equalsIgnoreCase("tari")) {
            infogame.setIcon(new javax.swing.ImageIcon(getClass().getResource(tari)));
        }else if (info.equalsIgnoreCase("masjid")) {
             infogame.setIcon(new javax.swing.ImageIcon(getClass().getResource(masjid)));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        infogame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 120, 30));

        infogame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tebk/harimau.png"))); // NOI18N
        getContentPane().add(infogame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new Game().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infogame;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
