/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzle_tebakakuu;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
/**
 *
 * @author persada
 */
public class Game extends javax.swing.JFrame {
 CardLayout cl;
 
    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        
        
         cards.add(new Home(this, cards), "Home");
         cards.add(new Puzzle(new ImageIcon(main.class.getResource("cend.png")).getImage()), "play1");
         cards.add(new Puzzle(new ImageIcon(main.class.getResource("mel.png")).getImage()), "play2");
         cards.add(new Puzzle(new ImageIcon(main.class.getResource("PangeranAntasari.png")).getImage()), "play3");
         cards.add(new Puzzle(new ImageIcon(main.class.getResource("sila5.png")).getImage()), "play4");
         cards.add(new Puzzle(new ImageIcon(main.class.getResource("pol.png")).getImage()), "play5");
         cards.add(new Puzzle(new ImageIcon(main.class.getResource("jokowi.png")).getImage()), "play6");
         cards.add(new Puzzle(new ImageIcon(main.class.getResource("sumatera.png")).getImage()), "play7");
         cards.add(new Puzzle(new ImageIcon(main.class.getResource("rumahadat.png")).getImage()), "play8");
         cards.add(new Puzzle(new ImageIcon(main.class.getResource("tarii.png")).getImage()), "play9");
         cards.add(new Puzzle(new ImageIcon(main.class.getResource("masjiid.png")).getImage()), "play10");
         //        cards.add(new Play().getFrame(), "play");
        cl = (CardLayout) cards.getLayout();
        cl.show(cards, "Home");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cards = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(655, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cards.setLayout(new java.awt.CardLayout());
        getContentPane().add(cards, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cards;
    // End of variables declaration//GEN-END:variables

    
}
