/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzle_tebakakuu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author persada
 */
public class loginnew extends javax.swing.JFrame {

    /**
     * Creates new form loginnew
     */
    public loginnew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernamefield = new javax.swing.JTextField();
        passwordfield = new javax.swing.JTextField();
        lbl_username = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(655, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernamefield.setMinimumSize(new java.awt.Dimension(8, 20));
        usernamefield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernamefieldKeyReleased(evt);
            }
        });
        getContentPane().add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 210, 40));

        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });
        passwordfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordfieldKeyReleased(evt);
            }
        });
        getContentPane().add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 210, 40));
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 190, -1));
        getContentPane().add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 200, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle_tebakakuu/Masuk.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 644, 476));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (usernamefield.getText().trim().isEmpty() && passwordfield.getText().trim().isEmpty()) {
            lbl_username.setText("username kosong");
            lbl_password.setText("password kosong");
            
            
        }
        else if (usernamefield.getText().trim().isEmpty()) {
            lbl_username.setText("username kosong");
            
        }else if (passwordfield.getText().trim().isEmpty()) {
            lbl_password.setText("password kosong");
            
        }else
            
        
        try{
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/puz","root","");
        ResultSet rs = con.createStatement().executeQuery("select * from siswa where username ='"+usernamefield.getText()+"'and password ='"+String.valueOf(passwordfield.getText())+"'");
             if (rs.next()) {
               
                 homee h = new homee ();
                 h.setVisible(true);
                 this.dispose();
               
                 
             }else{
                 JOptionPane.showMessageDialog(rootPane,"Masukkan username dan password dengaan benar");
                 
             
                     }
         }catch(SQLException ex) {
             
             }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldActionPerformed

    private void usernamefieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernamefieldKeyReleased
        lbl_username.setText("");
    }//GEN-LAST:event_usernamefieldKeyReleased

    private void passwordfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordfieldKeyReleased
        lbl_password.setText("");
    }//GEN-LAST:event_passwordfieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginnew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginnew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginnew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginnew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginnew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTextField passwordfield;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
